

## 什么是 Promise

Promise 是一种异步编程的解决方案。所谓 Promise ，可以理解为一个容器，里面保存着一个异步操作的结果。从语法上来说，它是一个对象，可以获取异步操作的消息。 Promise 提供统一的 API，各种异步操作都可以用同样的方法进行处理。

## 特点

>Promise对象有以下两个特点。

>（1）对象的状态不受外界影响。Promise对象代表一个异步操作，有三种状态：`Pending`（进行中）、`Fulfilled`（已成功）和 `Rejected`（已失败）。只有异步操作的结果，可以决定当前是哪一种状态，任何其他操作都无法改变这个状态。这也是 Promise 这个名字的由来，它的英语意思就是“承诺”，表示其他手段无法改变。

>（2）一旦状态改变，就不会再变，任何时候都可以得到这个结果。Promise 对象的状态改变，只有两种可能：从 Pending 变为 Fulfiled 和从 Pending 变为 Rejected。只要这两种情况发生，状态就凝固了，不会再变了，会一直保持这个结果，这时就称为 Resolved（已定型）。如果改变已经发生了，你再对 Promise 对象添加回调函数，也会立即得到这个结果。这与事件（Event）完全不同，事件的特点是，如果你错过了它，再去监听，是得不到结果的。

>有了 Promise 对象，就可以将异步操作以同步操作的流程表达出来，避免了层层嵌套的回调函数。此外，Promise 对象提供统一的接口，使得控制异步操作更加容易。

>Promise 也有一些缺点。首先，无法取消 Promise ，一旦新建它就会立即执行，无法中途取消。其次，如果不设置回调函数，Promise 内部抛出的错误，不会反应到外部。第三，当处于 Pending 状态时，无法得知目前进展到哪一个阶段（刚刚开始还是即将完成）。
>——摘自[阮一峰的《ECMAScript 6 入门》](http://es6.ruanyifeng.com/#docs/promise)

关于 Promise 的执行顺序，在 Promise 新建的时候，就会执行；定义的 `then` 回调函数，将会在顺序执行完所有程序后，才会执行。

```
let promise = new Promise(function(resolve, reject) {
  console.log('Promise');
  resolve();
});

promise.then(function() {
  console.log('Resolved.');
});

console.log('Hi!');
```

上例会输出：

```
Promise
Hi!
Resolved.
```

关于 Promise 的状态依赖，如果某个 Promise 中使用另一个 Promise 作为参数，那么前面的 Promise 的状态将会根据后面的 Promise 状态变更而变更。如下例：

```javascript
let promise1 = new Promise((resolve, reject) => {
  console.log('promise1 running');
  setTimeout(() => reject('promise1 error'), 3000);
});
let promise2 = new Promise((resolve, reject) => {
  console.log('promise2 running');
  setTimeout(() => resolve(promise1), 1000);
});
promise2
  .then(result => {
    console.log('then run');
    console.log(result);
  })
  .catch(err => {
    console.log('catch run');
    console.log(err);
  });
```

上例输出结果：

```
promise1 running
promise2 running
catch run
promise1 error
```

实际的结果，会先输出 `promise1 running`，紧接着输出 `promise2 running`；等待三秒后，输出 `catch run` 然后输出 `promise1 error`。

所以，promise2 中的定时器需要 1 秒执行，而 promise1 中需要三秒执行，但是 promise2 则需要等待 promise1 的状态变更，才会执行。也就是说 promise1 的状态，决定了 promise2 的状态。

## `Promise.prototype.then` 方法

Promise 实例具有 `then` 方法，该方法绑定在 Promise.prototype 上。它的作用，是为 Promise 实例添加状态变更的回调函数。其中，第一个参数为 Resolved 的回调函数；第二个参数可选，为 Rejected 状态的回调函数。

该方法，返回一个新的 Promise 实例，所以可以使用链式写法。

## `Promise.prototype.catch` 方法

`catch` 方法是 `then(null, rejection)` 的别名。用于发生错误时执行的回调函数。

注意，不要在 `resolve` 之后抛出异常，这样将无法捕获。
>因为 Promise 的状态一旦改变，就永久保持该状态，不会再变了。

## `Promise.all` 方法

该方法用于将多个 Promise 实例封装成一个新的 Promise 实例。

```javascript
var promise = Promise.all([p1, p2, p3]);
```

上例中，如果 p1，p2，p3 如果有不是 Promise 的实例的话，将会调用 Promise.resolve 方法，将实例转化为 Promise 实例，再进一步处理。

注意：
1. 只有当所有的实例的状态都变成 Fullfilled 时，Promise.all 对应的实例的状态才会变为 Fullfilled，然后将所有实例的返回值作为参数组成一个数组，传入 Promise 实例；
2. 若有一个实例的状态变为 Rejected，那么 Promise 实例的状态将会变为 Rejected，此时，第一个被 Rejected 的实例的返回值，将会作为参数，传入 Promise 实例的回调函数；
3. 如果作为参数的 Promise 实例自己定义了 `catch` 方法，那么当它状态变为 Rejected 的时候，并不会触发 Promise.all 的 `catch` 方法。

```javascript
let promise1 = new Promise((resolve, reject) => {
  resolve('promise 1 resolved');
})
.then(result => result)
.catch(err => console.log('promise 1 exception : ' + err));

let promise2 = new Promise((resolve, reject) => {
  throw new Error('throw from promise 2');
})
.then(result => result)
.catch(err => console.log('promise 2 exception : ' + err));

Promise.all([promise1, promise2])
.then(result => console.log('Promise all : ' + result))
.catch(err => console.log('Promise all error : ' + err));
```

上例输出结果：

```
promise 2 exception : Error: throw from promise 2
Promise all : promise 1 resolved,
```

从上例中，我们看到，promise2 在执行的时候，抛出了一个错误，但是由于 promise2 本身实现了 `catch` 方法。所以，这个错误被自己捕获到，正常执行完成后，这个 Promise 实例的状态被改变为 Resolved。所以，最终 Promise.all 并没有执行自己的 `catch`。

